### ISSUE TITLE
Missing of "0x00" in KDF, compared to NIST SP800-108(Revised, OCT 2009)

### ISSUE THREAD

**Issue by will-kong** [Microsoft/SecureDeviceConnectionProtocol#10]
I want to confirm whether the SDCP is designed to be different from SP-800, as to discard "0x00" in KDF ?

KDF described by wiki.
![wiki](https://user-images.githubusercontent.com/1670845/42306338-2dc105cc-8061-11e8-824d-f8923e60a4cc.PNG)

However, in NIST SP800-108, it is as follows:
![sp800-108](https://user-images.githubusercontent.com/1670845/42306464-abc6cc90-8061-11e8-9b61-6d4ce3352246.PNG)

**Comment by hacksoncode** [comment]
NIST doesn't define the label encoding, but the 0x00 here indicates that the label is null terminated..

The SDCP specifically calls out labels as being null terminated, so I don't think there's any actual difference other than nomenclature.
