### ISSUE TITLE
[Question] Default sensor/storage adapters for secure device

### ISSUE THREAD

**Issue by pbesson-invn** [Microsoft/SecureDeviceConnectionProtocol#12]
Hello,

[INF Changes](https://github.com/Microsoft/SecureDeviceConnectionProtocol/wiki/Secure-Device-Connection-Protocol#inf-changes) section indicates vendor sensor and sensor adapters must be provided when enabling SDCP.

Can we expect inbox adapters supporting SDCP? If not, is there some code available (or library) to limit errors/bugs (and spare me some time) in re-codding those adapters with their default behavior (or an updated version)?

Assuming the answer is no, can you confirm is it would be ok to remove WBDI driver and do all the sensor control logic from the sensor adapter?

Thanks you!

Regards,
Paul

**Comment by jdtw** [comment]
No, inbox adapters will not support SDCP. 

> Assuming the answer is no, can you confirm is it would be ok to remove WBDI driver and do all the sensor control logic from the sensor adapter?
Yes, for the most part. But even when using a custom sensor adapter, the driver must:
1. Publish the `GUID_DEVINTERFACE_BIOMETRIC_READER` interface
2. Support `IOCTL_BIOMETRIC_GET_ATTRIBUTES`
But besides that, the custom sensor adapter can communicate with the driver however it wants to.

**Comment by pbesson-invn** [comment]
Thanks @jdtw 

Can I still have SDCP working with the default **storage** adapter if we perform match on host?

**Comment by hacksoncode** [comment]
Match on host is not supported for SDCP.

Probably it would be a good idea to put a mention of that in the documentation, since currently it pretty strongly implies that it is.
