### ISSUE TITLE
[question] Clarification about `EngineAdapterIdentifyFeatureSetAuthenticated()` return values

### ISSUE THREAD

**Issue by pbesson-invn** [Microsoft/SecureDeviceConnectionProtocol#14]
Hello,

When doing an enrollment from Windows Hello, it starts by doing an identify by calling `EngineAdapterIdentifyFeatureSetAuthenticated()`, even when no finger are yet enroll on the device and the system.

In this case, and according to my understanding of the documentation of `EngineAdapterIdentifyFeatureSetAuthenticated()`, I return:
* `Identity` data set to zero
* `SubFactor` set to `WINBIO_SUBTYPE_NO_INFORMATION`
* `AuthenticationSize` set to zero.
* Return `S_OK` as `HRESULT`

This will cause Windows Hello to fail with “Something went wrong” message. The system event viewer indicates identification has failed with error `E_INVALIDARG`.

If I return `WINBIO_E_NO_MATCH`, the system event viewer indicates identification has failed with error `WINBIO_E_NO_MATCH`.

What should I return in case of failed authentication (because of no template on the device or wrong finger detected) ?

This blocks enrollment in Windows Hello but I would think it is expected to have a failed authentication in this case...

When doing enrollment from a test application using WBF Client Application APIs (skipping identification before starting enrollment), I can successfully complete an enrollment according to event viewer messages.

However, when attempting an identification, I will get the error `WINBIO_E_DATABASE_NO_RESULTS` event if finger is properly match and the secure id reported to the host. All HMAC checks are good on FW side.

Error is reported by the service after `EngineAdapterIdentifyFeatureSetAuthenticated()` has returned with all outputs set as follow:
* `Identity->Value.SecureId` set to the value given by `EngineAdapterCommitEnrollment()`
* `SubFactor` set to the value given in `EngineAdapterCommitEnrollment()`
* `AuthenticationSize` set to `WINBIO_SCP_DIGEST_SIZE_V1`
* `Authentication` set to pointer to internal engine adapter buffer containing the HMAC from the device
* Return `S_OK` as `HRESULT`

I have also check FW hash and device public key was consistent between secure connection.

Am I missing something?

I am testing using **build 17754**.

Thanks for any input!

Regards,
Paul

**Comment by jdtw** [comment]
For the first issue, try returning `WINBIO_E_UNKNOWN_ID` as per this documentation: https://docs.microsoft.com/en-us/windows/desktop/api/winbio_adapter/nc-winbio_adapter-pibio_engine_identify_feature_set_fn

For the second, @edbarrer can assist you in gathering logs.

**Comment by pbesson-invn** [comment]
Thanks @jdtw 

Returning `WINBIO_E_UNKNOWN_ID` allows me to go one step further.

I now get the "Something went wrong" message after `EngineAdapterUpdateEnrollment()` returns `WINBIO_I_MORE_DATA` after processing the first sample. 

Note, I have the same behavior with our previous MoH certified device that does not support SDCP.
When disabling SDCP at system level and rebooting, old device works again.

I will wait for @edbarrer for further instructions.

Thanks.

**Comment by edbarrer** [comment]
I will respond offline for instructions to gather the logs.

**Comment by pbesson-invn** [comment]
Second issue fixed after clean install of RS5 official release
