### ISSUE TITLE
Questions about SDCP

### ISSUE THREAD

**Issue by AlphaLee** [Microsoft/SecureDeviceConnectionProtocol#15]
Hello,
After reading the SDCP wiki documentation, I have some questions about SDCP.
1. Match on host is not supported for SDCP?
2. How can I program to generate vsmEngineAdapterBinary, vsmSensorAdapterBinary, and vsmStorageAdapterBinary, Is there any document about how to guide us program in the trusted execution environment?
3. Any requirements for platform to do SDCP demo? Because I program a version 6 SensorAdapter Interface demo which implements nothing in new api, for example,

```
//
// Additional methods available in V6.0 and later
//
static HRESULT 
WINAPI
SensorAdapterConnectSecure(
        _Inout_ PWINBIO_PIPELINE Pipeline,
	_In_ const WINBIO_SECURE_CONNECTION_PARAMS* ConnectionParams,
	_Outptr_ WINBIO_SECURE_CONNECTION_DATA** ConnectionData
)
{
	TRACE(_T("SensorAdapter-> SensorAdapterConnectSecure\n"));
	return S_OK;
}
```
depending on the log infomation it seems that WBS does not call the new API SensorAdapterConnectSecure.
Event viewer report the information as the following, I suspect this may impact the SDCP and some requirements does not meet the SDCP.
![secure component fail](https://user-images.githubusercontent.com/43718595/46657278-78879900-cbe2-11e8-89b1-95383cfeec12.png)

Could anyone explain those? Thank you.

**Comment by mapalko** [comment]
Match on host is not supported for SDCP at this time. vsmEngineAdapterBinary, vsmSensorAdapterBinary, and vsmStorageAdapterBinary must be set to WinBioVsmNullAdapter in the inf. WinBioVsmNullAdapter is an inbox Windows component. For SDCP, a vendor does not develop any components that run in the VSM TEE.

**Comment by AlphaLee** [comment]
@mapalko 

Hi mapalko,

I still have some questions. How can I ensure vendor SensorAdapter works? 

Because I want to test Secure Connection Protocol, The API SensorAdapterConnectSecure MUST be called by WBF firstly, Unfortunately It doesn't work and the Event Viewer biometric log report 0x80098033 which means the biometric unit could not be configured.
I have done the following work, wishing you to point out the problems:
1.  modify the inf for SDCP as mentioned in the wiki
`
HKR,WinBio\Configurations,VirtualSecureConfiguration,0x00010001,0x00000001
HKR,WinBio\Configurations\1,DatabaseId,,"4D2F33B8-7C24-4533-9E5A-FE484EE80127"
HKR,WinBio\Configurations\1,EngineAdapterBinary,,"MySecureEngineAdapter.dll"
HKR,WinBio\Configurations\1,SensorAdapterBinary,,"MySecureSensorAdapter.dll"
HKR,WinBio\Configurations\1,StorageAdapterBinary,,"MySecureStorageAdapter.dll"
HKR,WinBio\Configurations\1,VsmEngineAdapterBinary,,"WinBioVsmNullAdapter"
HKR,WinBio\Configurations\1,VsmSensorAdapterBinary,,"WinBioVsmNullAdapter"
HKR,WinBio\Configurations\1,VsmStorageAdapterBinary,,"WinBioVsmNullAdapter"
HKR,WinBio\Configurations\1,SensorMode,0x00010001,0x00000002            
HKR,WinBio\Configurations\1,SystemSensor,0x00010001,0x00000001         
HKR,WinBio\Configurations\1,VirtualSecureMode,0x00010001,0x00000001
 `

2. Generate the vendor Adapters which may not support SDCP. BUT I think it does't matter, because I just want to test Secure Connection Protocol. 

3. System version is RS4 1803(Build 17134.1).

4. PC have the TPM2.0 module.

 Looking forward to your reply, thank you.

**Comment by AlphaLee** [comment]
In addition, Windows SDK 17134 seem that the related var in struct WINBIO_SECURE_CONNECTION_PARAMS & WINBIO_SECURE_CONNECTION_DATA has been commented. I want to know is there a NEW SDK update?
![windows 17134 sdk](https://user-images.githubusercontent.com/43718595/47211465-15f38180-d3c8-11e8-9abf-61c0a2ce5b9a.PNG)

**Comment by pbesson-invn** [comment]
@AlphaLee Structure fields are commented on purpose because actual object size may vary depending on context. The un-commented field allows to determine the actual object size and retrieve each field separately. 
However, newer SDK will add `IntermediateCA1Size` and `IntermediateCA1Size` to the `_WINBIO_SECURE_CONNECTION_DATA` struct header.

**Comment by mapalko** [comment]
@AlphaLee, there are some bugs with this in the 1803 release. Please use the 1809 release of Windows and the 1809 SDK. You will need to add the following reg key to use the new APIs: [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\DeviceGuard\Scenarios\SecureBiometrics]
"Enabled"=dword:00000000

**Comment by hacksoncode** [comment]
I'm not in a place where I can just check our code, but was that supposed to be Enabled=0 or Enabled=1?

**Comment by AlphaLee** [comment]
> 
> 
> @AlphaLee Structure fields are commented on purpose because actual object size may vary depending on context. The un-commented field allows to determine the actual object size and retrieve each field separately.
> However, newer SDK will add `IntermediateCA1Size` and `IntermediateCA1Size` to the `_WINBIO_SECURE_CONNECTION_DATA` struct header.

I got it. Thank you.

**Comment by AlphaLee** [comment]
> 
> 
> @AlphaLee, there are some bugs with this in the 1803 release. Please use the 1809 release of Windows and the 1809 SDK. You will need to add the following reg key to use the new APIs: [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\DeviceGuard\Scenarios\SecureBiometrics]
> "Enabled"=dword:00000001

Hi @mapalko 

I have updated the 1809 release SDK & Windows, and add the reg key mentioned by you.Unfortunately still not work and Event Viewer biometric log report 0x80098033.
I use the Procmon tool to monitor the driver, finding that the VendorAdaptor.dll isn't loaded by WBS. It seems that the configuration or unsatisfactory platform leaded to the error. I am sure that the driver inf have followed SDCP wiki. Is there any platform requirements for SDCP demo? OR, can you recommend a Laptop model for SDCP?
