### ISSUE TITLE
I wonder dose one secure connect have a timeliness?

### ISSUE THREAD

**Issue by FengJungle** [microsoft/SecureDeviceConnectionProtocol#21]
I am testing secure connect on system (20H2, 20128/20140) with fingerprint device. I found one confusing case. 

One complete fingerprint enroll needs user to touch 12 times. During enrollment, I leave for other work for about 5 min (maybe I just touch 5 times, for example) . When I came back to continue to finish the left 7 times, the windows hello unit showed: something went wrong. 

I was confused and then test more. I ensure that the fingerprint device remains in its working state.  I found if the time I leave was limited within about 4 mins, I can finish enrollment successfully. Leaving more than 5 mins would lead to an unsuccessful enrollment. (Always show "something went  wrong".

I doubt whether the secure connection has a timeliness? Is there a document explaining this case?
![WeChat Image_20200615044229](https://user-images.githubusercontent.com/32355651/84653784-de055000-aec2-11ea-8636-7dd983d92e34.jpg)

**Comment by mamckee** [comment]
The timeout is not due to the SDCP. Enrollment for secure biometrics times out after 5 minutes from entering PIN. The timeout is to help ensure only the authorized user is enrolling their biometrics.

**Comment by FengJungle** [comment]
> The timeout is not due to the SDCP. Enrollment for secure biometrics times out after 5 minutes from entering PIN. The timeout is to help ensure only the authorized user is enrolling their biometrics.


Hi, thanks for your kindly reply. 
**But when I disable VBS, during enrollment, I pause for over 5 minutes, even 8min, but I can finish enrollment successfully.** This is different from thest behaviors in VBS.

**Comment by mamckee** [comment]
Yes, in the secure bio case, the timeout guarantees that biometrics were enrolled within a reasonable time from entering PIN. In the normal bio case, this guarantee cannot be made. The secure biometric enrollments are cryptographically tied to the user's PIN, while normal biometrics are not. Even though the settings flow requires the user's PIN, enrollments can still be added to the template database without PIN. The user's PIN is only required to enable biometrics as a sign in option when they enroll the first time.

**Comment by FengJungle** [comment]
> Yes, in the secure bio case, the timeout guarantees that biometrics were enrolled within a reasonable time from entering PIN. In the normal bio case, this guarantee cannot be made. The secure biometric enrollments are cryptographically tied to the user's PIN, while normal biometrics are not. Even though the settings flow requires the user's PIN, enrollments can still be added to the template database without PIN. The user's PIN is only required to enable biometrics as a sign in option when they enroll the first time.

Hi mamckee, thanks for your timely reply and detailed explanation.
And I have another question.  Is there a document or website describing the machanism or the exact time? Actually, I tested more cases, and recorded the pause time and result:
4:25 success
4:21 success
4:30 success
4:56 fail
4:59 fail
5:08 fail
5:12 fail
over 7min fail

Thank you a lot!

**Comment by FengJungle** [comment]
> Yes, in the secure bio case, the timeout guarantees that biometrics were enrolled within a reasonable time from entering PIN. In the normal bio case, this guarantee cannot be made. The secure biometric enrollments are cryptographically tied to the user's PIN, while normal biometrics are not. Even though the settings flow requires the user's PIN, enrollments can still be added to the template database without PIN. The user's PIN is only required to enable biometrics as a sign in option when they enroll the first time.

Hi mamckee, got it! Thanks for your timely reply and detailed explanation. 
 I wonder is there a document or website describing this mechanism?

**Comment by mamckee** [comment]
I'm not aware of any documentation with this behavior yet, but this should be documented. Thanks for helping surface this!

**Comment by FengJungle** [comment]
> I'm not aware of any documentation with this behavior yet, but this should be documented. Thanks for helping surface this!

Received. 
Thank you!
