### ISSUE TITLE
[question] Securing templates and Enroll()/Identify() implementation with match-on-host sensor

### ISSUE THREAD

**Issue by pbesson-invn** [Microsoft/SecureDeviceConnectionProtocol#7]
Hello,

I have some questions regarding Secure Biometric with basic/advanced sensor. I hope it is an acceptable place to ask them. I apologize if not.

Looking at https://github.com/Microsoft/SecureDeviceConnectionProtocol/wiki/Secure-Device-Connection-Protocol#sample-collection-and-template-storage-layer-one it is said:

> For basic, _match-on-host_ senor in VSM, the biometric trustlet secures the templates, which are encrypted to VSM at rest. The remaining gap at this layer is raw biometric samples, which must pass through the untrusted OS on their way to the matcher.

In this scenario, the EngineAdapter will get the encrypted sample. It can decrypt it with `WbioFrameworkVsmDecryptSample()`, extract features and generate or load template using the default WinBio storage adapter.
- Can I considered the EngineAdapter to be secured since dll is signed (even if OS is compromised), or should I rely on a TEE (Intel SGX) for processing the sample data?

In case of a advanced, match-off-host sensors, templates should be stored on the device. 
- Is there a requirements on the number of templates the device should be able to store?
- If device don't have sufficient memory, could we consider doing the matching on the device while retrieving templates stored in the host? Documentation does not suggest this scenario but somewhat maybe could be achievable...

Thanks to anyone that can provides some input!

Regards,
Paul

**Comment by pbesson-invn** [comment]
Thank you very much :)

I will for sure get in touch if I have more questions!

**Comment by jdtw** [comment]
Happy to help. Closing this issue.
