### ISSUE TITLE
[Question] Host validate the certification

### ISSUE THREAD

**Issue by initialapex** [Microsoft/SecureDeviceConnectionProtocol#8]
The wiki mention:
> Verifies the claim :
> - `pk_m <- Validate(cert_m)`
> - `Verify(pk_m, H(pk_d), s_m)`
> - `Verify(pk_d, H(C001||h_f||pk_f), s_d)`
> - `Validate(h_f)`

I don't understand how `cert_m` could become public key of model (`pk_m`).

I saw that the source code mention:
> ``` c
>    // There is no support for real certificate validation yet.
>    // For now, just pass in the model public key in place of the
>    // ASN.1 DER encoded X509 cert.
>    uint8_t claim_hash[SDCP_DIGEST_SIZE_V1] = { 0 };
>    ASSERT_EQUAL(0, sdcpcli_hash_claim(
>        g_model_pub_key, sizeof(g_model_pub_key), // Pub key in place of cert for now.
>        device_key.pk, sizeof(device_key.pk),
>        firmware_key.pk, sizeof(firmware_key.pk),
>        &firmware_signature,
>        &model_signature,
>        claim_hash, sizeof(claim_hash)));
>    print_bytes("H(c)", claim_hash, sizeof(claim_hash));
> ```

It is hard to understand how the real product should response both `pk_m` and `cert_m` or just response `cert_m` from the device to host. 

Could anyone explain that?

**Comment by initialapex** [comment]
Sorry, I got the public key from the ECDSA certification.

**Comment by pbesson-invn** [comment]
Hello @initialapex 

I started integrating SDCP but the secure connection is rejected by the bio service without much detail about what is wrong.

I am using the test keys provided in the reference code and use the public key as `cert_m` for now. Don't know if this is the root cause of my problem...

Where you able to generate your own model key / certificate ? If yes, could you share how?

Thank you!

Regards,
Paul

**Comment by initialapex** [comment]
Hi @pbesson-invn

Not sure the cause of rejection, but you can try to use the self-signed certification instead public key.

Regards,
Scott

**Comment by pbesson-invn** [comment]
@initialapex thanks for your advice. I did try to generate my own self-signed ECDSA certificate with openssl but this does not fix the problem I have...

**Comment by initialapex** [comment]
@pbesson-invn Probably, the certification should be issued by MSFT. It is mentioned in the wiki as below.

> To that end, each secure sensor is REQUIRED to have a Microsoft-issued certificate with an ECDSA-capable public key, which is obtained (along with the corresponding private key) via certification. This certificate serves as proof that the host is talking to a sensor that it trusts.

I tried this library and build self-signed certificate in my own test program,  it is just checking functionality.

**Comment by pbesson-invn** [comment]
Yeah, I saw that. But at the same time, it is mentioned in comment cert checking is not enforced for now.

Thanks anyway for your help!

**Comment by prafulla-git** [comment]
@initialapex, could you explain more about and procedure used                     "I tried this library and build self-signed certificate in my own test program, it is just checking functionality."

**Comment by initialapex** [comment]
@prafulla-git I build a console application (.exe) to simulate the host / device data flow. The cert_m is generated by openssl. It is not related to real driver and device.

**Comment by AlphaLee** [comment]
Hi @pbesson-invn @prafulla-git ,
I am testing SDCP with WBS，BUT the WBS doesn't load the VendorAdapter.dll. Could you share your experience about it.  
Thank you!
