### ISSUE TITLE
[Question] Reconnect processing at sample code

### ISSUE THREAD

**Issue by initialapex** [Microsoft/SecureDeviceConnectionProtocol#9]
In sample code, reconnect just generate the host random for device to generate a MAC,

``` c
    // Now simulate a reconnect. The host will send new random bytes for
    // the client to MAC.
    puts("\nReconnect:\n----------\n");
    ASSERT_EQUAL(0, sdcpcli_gen_rand(host_random, sizeof(host_random)));
    print_bytes("r", host_random, sizeof(host_random));

    ASSERT_EQUAL(0, sdcpcli_mac_reconnect(
        &app_keys,
        host_random, sizeof(host_random),
        mac, sizeof(mac)));
    print_bytes("m", mac, sizeof(mac));
```

But it should derives application keys before generate a MAC that wiki described, right?

> 3. Device:
>      i. Derives application keys:
>            - `(s, k) <- KDF(ms, "application keys")`
>      ii. Generates a MAC over the r_h:
>            - `m <- MAC(s, "reconnect"||r_h)`
>      iii. Sends the `ReconnectResponse` message, containing `m`.

**Comment by jdtw** [comment]
The application keys `(s, k)` for the reconnect are the same as the ones from the original, full connection. So you have two options when doing a reconnect, depending on how memory-constrained your device is. You can either:

1. Persist `ms` in memory, and re-derive `(s, k)` like in the wiki, or
2. Persist `(s, k)` in memory, and then there's no need to re-derive them (this is what the sample code is doing).

Either way, as long as you end up with the same `(s, k)` as in the full connection, you can do either, depending on which works for you.

**Comment by initialapex** [comment]
Thanks for the explanation.
